import React from "react";
import type { Metadata } from "next";
import GetAllUsers from "../../lib/GetAllUsers";
import { User } from "../../lib/type.d";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Users page",
  description: "Generated by create next app",
};

async function Users() {
  const usersData: Promise<User[]> = GetAllUsers();
  const Data = await usersData;

  const content = (
    <section>
      <h2>
        <Link href="/" className="text-blue-500 font-bold  px-2">
          {" "}
          back to home
        </Link>
      </h2>
      <br />
      {Data.map((user) => {
        return (
          <>
            <p key={user.id} className="text-center font-extrabold text-2xl">
              <Link href={`/users/${user.id}`}>{user.username}</Link>
            </p>
            <br />
          </>
        );
      })}
    </section>
  );

  return content;
}

export default Users;
